# Generated by Django 5.1.5 on 2025-01-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0999_add_sla_fields'),
        ('documents', '1061_workflowactionwebhook_as_json'),
    ]

    operations = [
    ]
